tutorial/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import firstapp.views as views
from member import views as m_views
from map import views as map_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),
    path('polls/', include('polls.urls')),
    path('second/', include('secondapp.urls')),
    path('pagination/', include('pagination.urls')),
    # path('join/', include('member.urls')),
    path('join/',  m_views.join, name="join"),
    path('login2/',  m_views.login2, name="login2"),
    path('logout2/',  m_views.logout2, name="logout2"),
    path('upload1/',  m_views.upload1),
    path('download/', m_views.download),
    path('map/', map_views.map),
    path('map_data/', map_views.map_data),


    path(
        'login/', auth_views.LoginView.as_view(
            template_name='common/login.html'),
        name='login'),
    path(
        'logout/', auth_views.LogoutView.as_view(
            template_name='common/logout.html'),
        name='logout'),
    path('signup/', views.signup, name='signup'),  
]

tutorial/polls/urls.py
from django.urls import path, include
from . import views

app_name = 'polls' #namespace
urlpatterns = [
    path('', views.index, name='index'),  
    path('<int:question_id>/ ', views.detail,
        name='detail'),
    path(
        'answer/create/<int:question_id>/', views.answer_create,
        name='answer_create'),
    path(
        'question/create/', views.question_create,
        name='question_create'),
]

tutorial/polls/models.py
from django.db import models
from django.db.models.base import ModelState

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField()
    
    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.content

tutorial/polls/forms.py
from django import forms
from .models import Question

class QuestionForm(forms.ModelForm):    
    class Meta:
        model = Question
        fields = ['subject', 'content']

tutorial/polls/views.py
from polls.models import Question
from .forms import QuestionForm
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

def index(request):
    question_list = \
    Question.objects.order_by('-pub_date')
    return render(
        request, 'polls/question_list.html',
        {'question_list': question_list}
    )

    # result = [ q.subject for q in question_list ]
    # return JsonResponse(result, safe=False)
    # return HttpResponse( str(result) )

def detail(request, question_id):
    # question = \
    # Question.objects.get(pk=question_id)
    question = get_object_or_404(Question, id=question_id)
    
    return render(
        request, 'polls/question_detail.html',  
        {'question': question}
    )

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(
        content=request.POST.get('content'), 
        create_date=timezone.now())
    return redirect('/polls:detail/', question_id=question.id)
    
    # aa = request.POST.get('aa')
    # return HttpResponse(aa)

    # return redirect('/polls/%s/' % question_id)

def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('polls:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'polls/question_form.html', context)

tutorial/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css2/style.css' %}">

    <title>Document</title>
</head>
<body>
    {% block content %}
    
    {% endblock %}
</body>
</html>

tutorial/templates/polls/question_detail.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="container my-3">

    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ question.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.pub_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{question.answer_set.count}}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ answer.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'polls:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>

</div>
{% endblock %}

<!-- <h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>
<p>{{ question.answer_set.count }}개의 답변이 있습니다.</p>
<ul>
    {% for a in question.answer_set.all %}
    <li>{{ a.content }}</li>
    {% endfor %}
</ul>

<form action="{% url 'polls:answer_create' question.id %}" method="post">
    {% csrf_token%}
    {% comment %} <input type="text" name='aa'> {% endcomment %}
    <textarea name="content" id="content" rows="15"></textarea>
    <input type="submit" value="답변 등록">
</form> -->

tutorial/templates/polls/question_form.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

tutorial/templates/polls/question_list.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {% for question in question_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'polls:detail' question.id %}">
                        {{ question.subject }}
                    </a>
                </td>
                <td>{{ question.pub_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <a href="{% url 'polls:question_create' %}" class="btn btn-primary">
        질문 등록하기
    </a>
</div>
{% endblock %}
<!-- {% if question_list %}
<ul>
    {% for question in question_list %}
    <li>
        {% comment %} <a href="/polls/{{ question.id }}/"> {% endcomment %}
            <a href="{% url 'polls:detail' question.id %}">
                {{ question.subject }}
            </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>질문이 없습니다.</p>
{% endif %} -->